const dotenv = require('dotenv')

dotenv.config()

const {DB_URL, PORT, JWT_SECRET, EMAIL_USER, EMAIL_PASS,CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET} = process.env

const Config = {DB_URL, PORT, JWT_SECRET, EMAIL_USER, EMAIL_PASS,CLOUDINARY_API_KEY,CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_SECRET}

module.exports = Config